### ISSUE TITLE
Requesting maintainer access to emacs-oauth2-auto

### ISSUE THREAD

**Issue by telotortium** [telotortium/emacs-oauth2-auto#12]
Hi @rhaps0dy as discussed on https://github.com/rhaps0dy/emacs-oauth2-auto/pull/9#discussion_r1017084271 I would like to take over maintaining this repo.

**Comment by rhaps0dy** [comment]
Github doesn't let me trasnfer the repo because `telotortium/emacs-oauth2-auto` already exists. Could you please delete it and then reply here so I can do the transfer?

Thank you!

**Comment by telotortium** [comment]
@rhaps0dy Deleted - please transfer now.

**Comment by telotortium** [comment]
The transfer has gone through. Thank you!

**Comment by rhaps0dy** [comment]
Thank you for your work on `org-gcal` and all the associated stuff!!
