### ISSUE TITLE
Add to Melpa

### ISSUE THREAD

**Issue by telotortium** [telotortium/emacs-oauth2-auto#3]
This would make it easier to use in org-gcal (see https://github.com/kidd/org-gcal.el/pull/200).

**Comment by telotortium** [comment]
Instructions for Melpa are at https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org. We should merge #4 and #5 before adding to Melpa.

**Comment by MartinNowak** [comment]
Seems to have been fixed.
I [submitted a recipe to melpa](https://github.com/melpa/melpa/pull/8716) for org-caldav and to replace the vendored version in https://github.com/kidd/org-gcal.el/pull/200.

**Comment by MartinNowak** [comment]
Seems to be ready @telotortium.
I [submitted a recipe to melpa](https://github.com/melpa/melpa/pull/8716) for org-caldav and to replace the vendored version in https://github.com/kidd/org-gcal.el/pull/200.

**Comment by boogsbunny** [comment]
This package has already been added to [MELPA](https://melpa.org/#/oauth2-auto), so you can close this issue.
